version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:17"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "python"
    groups:
      python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:37"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    groups:
      github-actions:
        patterns:
          - "*"

